version: "3.5"

services:
  ingestion:
    #build: .
    image: ingestion
    hostname: ingestion
    container_name: ingestion
    volumes:
     - ./example:/example
     - ./databuilder:/databuilder
     - ./tmp:/var/tmp
    #command: python3 example/scripts/sample_data_loader.py es_amundsen neo4j_amundsen
    command: tail -f /dev/null

    networks:
        - amundsennet

networks:
  amundsennet:   
    name: amundsennet